### ISSUE TITLE
Can't Find Movies with Short Titles (but they exist on IMDB)

### ISSUE THREAD

**Issue by dropcase** [mlava/imdb#2]
Tried to add the movie F/X (1986) but searching doesn't give any results, and I get `Uncaught (in promise) TypeError: Cannot read property 'filter' of undefined` in the dev console. IMDB link:

[F/X (1986) - IMDb](https://www.imdb.com/title/tt0089118/)

Searched using:

- FX
- F/X
- FX (1986)
- F/X (1986)

I also tried some of the other titles listed here: [Sort by Popularity - Most Popular Movies and TV Shows tagged with keyword "slash-in-title" - IMDb](https://www.imdb.com/search/keyword/?keywords=slash-in-title) in case the `/` was the issue, but several worked without a problem.

It may be an issue with minimum character length for search, I got the same thing for `Ed` and `Up` - any way to resolve that, or to have a way to use the (known) IMDB ID to pull the data? Thanks!

**Comment by mlava** [comment]
Thanks for reporting @dropcase 
I will look into it.
Cheers!

**Comment by mlava** [comment]
Thanks @dropcase 
I hadn't come across this issue before, but it was a short title length that was the issue.
I've created a fix and confirmed it's working for F/X, Up and Ed.
It's awaiting review and approval in Roam Depot by the Roam team. Once it's updated, please let me know if you have any further issues.
Cheers!
