### ISSUE TITLE
IMDB score included in retrieval

### ISSUE THREAD

**Issue by emway66** [mlava/imdb#3]
Hi, is it possible to include the IMDB score in the retrieval? Would be a nice addition.

Thnx for your work.

**Comment by mlava** [comment]
Thanks @emway66 it's a good idea.

Implemented in https://github.com/Roam-Research/roam-depot/pull/495 You just need to wait for the PR to be reviewed and accepted by the Roam team.

Cheers!

**Comment by mlava** [comment]
![image](https://user-images.githubusercontent.com/6857790/216218626-bc2d1c98-622f-49fc-972b-e1c8e85613f2.png)

**Comment by mlava** [comment]
@emway66 this is now available. just refresh your browser to get the new version installed and it should update automatically
